development:
  mysql41: 9306
test:
  mysql41: 9307
production:
  mysql41: 9309
  pid_file: /var/www/html/invest_plan/shared/tmp/pids/searchd.pid
  indices_location: /var/www/html/invest_plan/shared/db/sphinx
  configuration_file: /var/www/html/invest_plan/shared/config/production.sphinx.conf
  binlog_path: /var/www/html/invest_plan/shared/tmp/binlog
